[project]
name = "ai-resume-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "debugpy>=1.8.20",
    "fastmcp>=2.14.5",
    "pylatex>=1.4.2",
]
